#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>
#include <math.h>
using namespace std;

int main(){
    double phi = (sqrt(5)+1)/2;
    double sum = 0;
    for(int i = 3; i<34; i=i+3){
        cout << round(pow(phi, i)/sqrt(5)) << endl;
        sum += round(pow(phi, i)/sqrt(5));
    }
    cout << sum;
} 
